Repository taha-yasin/blood-donor-backend, pull requests merged in 2022-03, with the labels that each got.

#9 fix ROLE_USER not assign to user
  src/main/java/io/tahayasin/blood_donor/service/AppUserService.java
  src/main/java/io/tahayasin/blood_donor/service/BloodRequestService.java
Labels: fix

#10 Add email based confirmation for new user
  src/main/java/io/tahayasin/blood_donor/BloodDonorApplication.java
  src/main/java/io/tahayasin/blood_donor/domain/AppUser.java
  src/main/java/io/tahayasin/blood_donor/domain/ConfirmationToken.java
  src/main/java/io/tahayasin/blood_donor/repos/AppUserRepository.java
  src/main/java/io/tahayasin/blood_donor/rest/ConfirmationTokenController.java
  src/main/java/io/tahayasin/blood_donor/security/AppUserDetailsService.java
  src/main/java/io/tahayasin/blood_donor/service/AppUserService.java
  src/main/java/io/tahayasin/blood_donor/service/ConfirmationTokenService.java
  src/main/java/io/tahayasin/blood_donor/service/DonorService.java
  src/main/java/io/tahayasin/blood_donor/service/EmailService.java
  src/main/java/io/tahayasin/blood_donor/twillio/Service.java
  src/main/java/io/tahayasin/blood_donor/twillio/SmsController.java
  src/main/java/io/tahayasin/blood_donor/twillio/SmsRequestDto.java
  src/main/java/io/tahayasin/blood_donor/twillio/TwilioConfiguration.java
  src/main/java/io/tahayasin/blood_donor/twillio/TwilioInitializer.java
  src/main/java/io/tahayasin/blood_donor/twillio/TwilioSmsSender.java
Labels: documentation, enhancement

#13 Change email template
  src/main/java/io/tahayasin/blood_donor/rest/AppRoleController.java
  src/main/java/io/tahayasin/blood_donor/rest/AppUserController.java
  src/main/java/io/tahayasin/blood_donor/rest/BloodRequestController.java
  src/main/java/io/tahayasin/blood_donor/rest/DonorController.java
  src/main/java/io/tahayasin/blood_donor/service/EmailService.java
  src/main/java/io/tahayasin/blood_donor/twillio/Service.java
  src/main/java/io/tahayasin/blood_donor/twillio/SmsController.java
  src/main/java/io/tahayasin/blood_donor/twillio/SmsRequestDto.java
  src/main/java/io/tahayasin/blood_donor/twillio/TwilioConfiguration.java
  src/main/java/io/tahayasin/blood_donor/twillio/TwilioInitializer.java
  src/main/java/io/tahayasin/blood_donor/twillio/TwilioSmsSender.java
Labels: enhancement
